const express=require("express");
const path=require("node:path");
const fs=require("node:fs");
const crypto=require("node:crypto");
const multer=require("multer");
const Stripe=require("stripe");
const app=express();
const port=process.env.PORT===undefined?3000:Number(process.env.PORT);
const ADMIN_EMAIL=String(process.env.ADMIN_EMAIL||"cool.bacon323@gmail.com").trim().toLowerCase();
const VERSION="0.5.0";
app.disable("x-powered-by");
const dataDir=path.join(__dirname,"data"),uploadDir=path.join(dataDir,"uploads");
fs.mkdirSync(uploadDir,{recursive:true});
const files={users:path.join(dataDir,"users.json"),games:path.join(dataDir,"games.json"),sessions:path.join(dataDir,"sessions.json"),purchases:path.join(dataDir,"purchases.json")};
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,"utf8"))}catch{return fallback}}
function writeJson(file,value){const tmp=file+".tmp";fs.writeFileSync(tmp,JSON.stringify(value,null,2),"utf8");fs.renameSync(tmp,file)}
for(const [file,value] of Object.entries(files))if(!fs.existsSync(file))writeJson(file,value);
function cleanUser(u){return{id:u.id,name:u.name,email:u.email,isAdmin:u.email===ADMIN_EMAIL}}
function hashPassword(password){const salt=crypto.randomBytes(16).toString("hex");return salt+":"+crypto.scryptSync(password,salt,64).toString("hex")}
function verifyPassword(password,stored){try{const [salt,hash]=String(stored||"").split(":");if(!salt||!hash)return false;const test=crypto.scryptSync(password,salt,64).toString("hex");return hash.length===test.length&&crypto.timingSafeEqual(Buffer.from(hash,"hex"),Buffer.from(test,"hex"))}catch{return false}}
function cookieToken(req){const m=String(req.headers.cookie||"").match(/(?:^|;\\s*)eg_session=([^;]+)/);return m?m[1]:null}
function getUser(req){const token=req.headers.authorization?.startsWith("Bearer ")?req.headers.authorization.slice(7):cookieToken(req);if(!token)return null;const id=readJson(files.sessions,{})[token];return readJson(files.users,[]).find(u=>u.id===id)||null}
function auth(req,res,next){const user=getUser(req);if(!user)return res.status(401).json({error:"You must be logged in."});req.user=user;next()}
function admin(req,res,next){if(req.user?.email!==ADMIN_EMAIL)return res.status(403).json({error:"Admin access required."});next()}
function tokenFor(user){const token=crypto.randomBytes(32).toString("hex");const sessions=readJson(files.sessions,{});sessions[token]=user.id;writeJson(files.sessions,sessions);return token}
function setCookie(res,token){res.setHeader("Set-Cookie","eg_session="+token+"; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000")}
function publicGame(g,owned=new Set()){return{id:g.id,title:g.title,description:g.description,price:g.price,creatorName:g.creatorName,status:g.status,createdAt:g.createdAt,owned:owned.has(g.id)}}
function purchaseExists(userId,gameId){return readJson(files.purchases,[]).some(p=>p.userId===userId&&p.gameId===gameId&&p.status==="paid")}
function grantPurchase({userId,gameId,stripeSessionId=null,paymentIntentId=null}){const purchases=readJson(files.purchases,[]);const existing=purchases.find(p=>p.stripeSessionId===stripeSessionId||(p.userId===userId&&p.gameId===gameId&&p.status==="paid"));if(existing)return existing;const purchase={id:crypto.randomUUID(),userId,gameId,stripeSessionId,paymentIntentId,status:"paid",createdAt:new Date().toISOString()};purchases.push(purchase);writeJson(files.purchases,purchases);return purchase}
function stripeClient(){if(!process.env.STRIPE_SECRET_KEY){const e=new Error("STRIPE_SECRET_KEY is not configured.");e.statusCode=500;throw e}return new Stripe(process.env.STRIPE_SECRET_KEY)}
app.post("/api/stripe/webhook",express.raw({type:"application/json"}),(req,res)=>{try{const stripe=stripeClient();if(!process.env.STRIPE_WEBHOOK_SECRET)return res.status(500).json({error:"STRIPE_WEBHOOK_SECRET is not configured."});const event=stripe.webhooks.constructEvent(req.body,req.headers["stripe-signature"],process.env.STRIPE_WEBHOOK_SECRET);if(event.type==="checkout.session.completed"||event.type==="checkout.session.async_payment_succeeded"){const session=event.data.object;if(session.payment_status==="paid"||event.type.endsWith("succeeded")){const userId=session.metadata?.userId,gameId=session.metadata?.gameId;if(userId&&gameId)grantPurchase({userId,gameId,stripeSessionId:session.id,paymentIntentId:typeof session.payment_intent==="string"?session.payment_intent:null})}}res.json({received:true})}catch(error){console.error("Stripe webhook:",error.message);res.status(400).json({error:"Invalid Stripe webhook."})}});
app.use(express.json({limit:"2mb"}));
app.use(express.static(__dirname,{index:"index.html",dotfiles:"ignore"}));
app.get("/api/health",(req,res)=>res.json({ok:true,service:"extra-games",version:VERSION}));
app.get("/api/auth/me",(req,res)=>{const user=getUser(req);res.json({user:user?cleanUser(user):null})});
app.post("/api/auth/signup",(req,res)=>{const name=String(req.body?.name||"").trim(),email=String(req.body?.email||"").trim().toLowerCase(),password=req.body?.password;if(!name||name.length>32||!/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email)||typeof password!=="string"||password.length<8)return res.status(400).json({error:"Use a valid name, email and password of at least 8 characters."});const users=readJson(files.users,[]);if(users.some(u=>u.email===email))return res.status(409).json({error:"An account with that email already exists."});const user={id:crypto.randomUUID(),name,email,password:hashPassword(password),createdAt:new Date().toISOString()};users.push(user);writeJson(files.users,users);setCookie(res,tokenFor(user));res.json({user:cleanUser(user)})});
app.post("/api/auth/login",(req,res)=>{const email=String(req.body?.email||"").trim().toLowerCase(),user=readJson(files.users,[]).find(u=>u.email===email);if(!user||!verifyPassword(String(req.body?.password||""),user.password))return res.status(401).json({error:"Invalid email or password."});setCookie(res,tokenFor(user));res.json({user:cleanUser(user)})});
app.post("/api/auth/logout",(req,res)=>{const token=req.headers.authorization?.startsWith("Bearer ")?req.headers.authorization.slice(7):cookieToken(req);if(token){const sessions=readJson(files.sessions,{});delete sessions[token];writeJson(files.sessions,sessions)}res.setHeader("Set-Cookie","eg_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0");res.json({ok:true})});
const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>cb(null,crypto.randomUUID()+path.extname(file.originalname).toLowerCase())}),limits:{fileSize:2*1024*1024*1024},fileFilter:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase();cb(ext===".zip"||ext===".exe"?null:new Error("Only .zip and .exe game packages are allowed."))}});
app.post("/api/games/upload",auth,upload.single("game"),(req,res)=>{if(!req.file)return res.status(400).json({error:"Choose a ZIP or EXE game package."});const title=String(req.body?.title||"").trim(),description=String(req.body?.description||"").trim(),price=Number(req.body?.price);if(!title||title.length>80||!description||description.length>2000||!Number.isFinite(price)||price<0||price>999.99){fs.rmSync(req.file.path,{force:true});return res.status(400).json({error:"Enter a valid title, description and price from €0 to €999.99."})}const game={id:crypto.randomUUID(),title,description,price:Math.round(price*100)/100,filename:req.file.filename,originalFilename:req.file.originalname,creatorId:req.user.id,creatorName:req.user.name,status:"pending",createdAt:new Date().toISOString()};const games=readJson(files.games,[]);games.push(game);writeJson(files.games,games);res.json({game:publicGame(game)})});
app.get("/api/games",(req,res)=>{const user=getUser(req),owned=new Set(user?readJson(files.purchases,[]).filter(p=>p.userId===user.id&&p.status==="paid").map(p=>p.gameId):[]);res.json({games:readJson(files.games,[]).filter(g=>g.status==="approved").map(g=>publicGame(g,owned))})});
app.get("/api/library",auth,(req,res)=>{const owned=new Set(readJson(files.purchases,[]).filter(p=>p.userId===req.user.id&&p.status==="paid").map(p=>p.gameId));res.json({games:readJson(files.games,[]).filter(g=>owned.has(g.id)).map(g=>publicGame(g,owned))})});
app.get("/api/admin/games",auth,admin,(req,res)=>res.json({games:readJson(files.games,[]).map(g=>publicGame(g))}));
for(const action of ["approve","reject"])app.post("/api/admin/games/:id/"+action,auth,admin,(req,res)=>{const games=readJson(files.games,[]),game=games.find(g=>g.id===req.params.id);if(!game)return res.status(404).json({error:"Game not found."});game.status=action==="approve"?"approved":"rejected";writeJson(files.games,games);res.json({game:publicGame(game)})});
app.post("/api/create-checkout-session",auth,async(req,res)=>{try{const game=readJson(files.games,[]).find(g=>g.id===String(req.body?.gameId||"")&&g.status==="approved");if(!game)return res.status(404).json({error:"Game not found or not approved."});if(purchaseExists(req.user.id,game.id))return res.status(409).json({error:"You already own this game."});if(game.price===0){grantPurchase({userId:req.user.id,gameId:game.id});return res.json({free:true,gameId:game.id})}const stripe=stripeClient(),origin=process.env.PUBLIC_BASE_URL||req.protocol+"://"+req.get("host");const session=await stripe.checkout.sessions.create({mode:"payment",customer_email:req.user.email,line_items:[{price_data:{currency:"eur",product_data:{name:game.title,description:game.description.slice(0,500)},unit_amount:Math.round(game.price*100)},quantity:1}],metadata:{userId:req.user.id,gameId:game.id},success_url:origin+"/success.html?session_id={CHECKOUT_SESSION_ID}",cancel_url:origin+"/cancel.html"});res.json({url:session.url,sessionId:session.id})}catch(error){console.error("Checkout:",error);res.status(error.statusCode||500).json({error:error.message||"Payment service error."})}});
app.get("/api/purchases/confirm",auth,async(req,res)=>{try{const sessionId=String(req.query.session_id||"");if(!sessionId)return res.status(400).json({error:"Missing session_id."});const session=await stripeClient().checkout.sessions.retrieve(sessionId);if(session.metadata?.userId!==req.user.id||session.payment_status!=="paid")return res.status(403).json({error:"Payment is not confirmed for this account."});const purchase=grantPurchase({userId:req.user.id,gameId:session.metadata.gameId,stripeSessionId:session.id,paymentIntentId:typeof session.payment_intent==="string"?session.payment_intent:null});res.json({ok:true,purchase})}catch(error){res.status(400).json({error:error.message||"Could not confirm payment."})}});
app.get("/api/games/:id/download",auth,(req,res)=>{const game=readJson(files.games,[]).find(g=>g.id===req.params.id&&g.status==="approved");if(!game)return res.status(404).json({error:"Game not found."});if(!purchaseExists(req.user.id,game.id))return res.status(403).json({error:"Purchase this game before downloading it."});const root=path.resolve(uploadDir),filePath=path.resolve(uploadDir,game.filename);if(!filePath.startsWith(root+path.sep)||!fs.existsSync(filePath))return res.status(404).json({error:"Game package is unavailable."});res.download(filePath,game.originalFilename||path.basename(filePath))});
app.use((err,req,res,next)=>{console.error(err);if(res.headersSent)return next(err);res.status(400).json({error:err.message||"Request failed."})});
const server=app.listen(port,()=>console.log("Extra Games "+VERSION+" listening on port "+server.address().port));
module.exports={app,server};